### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [taehyunlim/splurtae#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by taehyunlim** [comment]
Hey Ken,
Thanks for the tip- that helped me tremendously!
Regarding the following meta tag, I was wondering what 'initial-scale=1' referred to. Could you give me just a high level explanation so that I have a general idea? 

'<' meta name="viewport" content="width=device-width, initial-scale=1" '>'

Btw, my app is finally responsive on mobile: splurtae.herokuapp.com 
Thanks again :)

**Comment by taehyunlim** [comment]
Oh, here's the meta tag I was referring to:

##<meta name="viewport" content="width=device-width, initial-scale=1">

**Comment by taehyunlim** [comment]
That

**Comment by kenmazaika** [comment]
Looks perfect!  Thumbs up :+1:

For a longer explanation checkout this video I made a few years ago.
https://vimeo.com/75718091
